<?php

namespace App\Filament\Resources\ZawaKonsultasiSubmissionResource\Pages;

use App\Filament\Resources\ZawaKonsultasiSubmissionResource;
use Filament\Resources\Pages\CreateRecord;
use App\Models\Service;

class CreateZawaKonsultasiSubmission extends CreateRecord
{
    protected static string $resource = ZawaKonsultasiSubmissionResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $service = Service::where('slug', 'zawa-konsultasi')->first();
        
        // Ensure content is structured correctly if needed, 
        // but since form schema uses 'content.field', it should be fine.
        // We set the service_id and tracking code here.
        
        $data['service_id'] = $service->id;
        $data['user_id'] = auth()->id();
        $data['status'] = 'pending';
        // Tracking code is usually generated by model boot, but if not:
        // $data['tracking_code'] = ...
        
        return $data;
    }
}
